[package]
name = "anydoc-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
anydoc = { path = ".." }
cfb = "0.14.0"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }

[[bin]]
name = "docx"
path = "fuzz_targets/docx.rs"
test = false
doc = false

[[bin]]
name = "rtf"
path = "fuzz_targets/rtf.rs"
test = false
doc = false

[[bin]]
name = "doc"
path = "fuzz_targets/doc.rs"
test = false
doc = false

[[bin]]
name = "ppt"
path = "fuzz_targets/ppt.rs"
test = false
doc = false

[[bin]]
name = "csv"
path = "fuzz_targets/csv.rs"
test = false
doc = false

[[bin]]
name = "odf"
path = "fuzz_targets/odf.rs"
test = false
doc = false

[[bin]]
name = "epub"
path = "fuzz_targets/epub.rs"
test = false
doc = false

[[bin]]
name = "xlsx"
path = "fuzz_targets/xlsx.rs"
test = false
doc = false

[[bin]]
name = "pdf"
path = "fuzz_targets/pdf.rs"
test = false
doc = false

[[bin]]
name = "xls"
path = "fuzz_targets/xls.rs"
test = false
doc = false

[[bin]]
name = "xlsb"
path = "fuzz_targets/xlsb.rs"
test = false
doc = false

[[bin]]
name = "numfmt"
path = "fuzz_targets/numfmt.rs"
test = false
doc = false
